export enum Gabarit {
    B_BRINE = "B_BRINE",
    MW_MARINE_WATER = "MW_MARINE_WATER",
    W_WATER = "W_WATER",
    C_ORE_CONC = "C_ORE_CONC",
    O_OTHER_SPECIFY = "O_OTHER_SPECIFY",
    P_PULP = "P_PULP",
    LS_LAKE_SEDIMENT = "LS_LAKE_SEDIMENT",
    HMC_HEAVY_MINERALS_CONCENTRATE = "HMC_HEAVY_MINERALS_CONCENTRATE",
    R_ROCK = "R_ROCK",
    CR_CRUSHED_ROCK = "CR_CRUSHED_ROCK",
    DC_DRILL_CORE = "DC_DRILL_CORE",
    H_HUMUS = "H_HUMUS",
    S_SOIL = "S_SOIL",
    V_VEGETATION = "V_VEGETATION",
    SS_STREAM_SEDIMENT = "SS_STREAM_SEDIMENT"
}